### ISSUE TITLE
Allow platformContext and geoContext tracking

### ISSUE THREAD

**Issue by ohitsdaniel** [HomeXLabs/snowplow-flutter-tracker#10]
https://github.com/snowplow/snowplow-objc-tracker/blob/5c3f00d9f9168a7089e5075f45ddfc27cb4c1582/Snowplow/SPSubject.m#L39

SPSubject allows to track the platform and geo context for tracking events. [Currently](https://github.com/HomeXLabs/snowplow-flutter-tracker/blob/65e92369019097c8272d2c8c954d74bc7d4b63a4/ios/Classes/TrackerUtil.swift#L13), we use the convenience initialiser that passes false for both contexts. Let's add support for geo and platform contexts.

**Comment by MisterJimson** [comment]
Do you think we should just set true or allow it to be set from the dart layer?

**Comment by ohitsdaniel** [comment]
I think we should allow it to be set from the dart layer and mimic all functionalities of the ObjC/Kotlin tracker builder on the dart side. :)

**Comment by mltbnz** [comment]
I can pick up this issue
