### ISSUE TITLE
Investigate logging on iOS

### ISSUE THREAD

**Issue by MisterJimson** [HomeXLabs/snowplow-flutter-tracker#7]
1. Create tracker with `logLevel: LogLevel.VERBOSE` 
2. Run example app as is on Android
3. Click buttons
4. See errors in console as expected since the example app does not point to a configured server

If you do the same but on iOS, you get no errors in the console.

**Comment by ohitsdaniel** [comment]
Hi @MisterJimson 👋 ,

I checked the iOS source code of this library and the log level is [not set when the tracker is created](https://github.com/HomeXLabs/snowplow-flutter-tracker/blob/main/ios/Classes/TrackerUtil.swift#L15). Therefore, no logging is visible in the console. 

To fix this, we will have to add SPTrackerBuilder?.setLogLevel to the calls in the builder block.

**Comment by ohitsdaniel** [comment]
Resolved in #13
